<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Quest;

class QuestSeeder extends Seeder
{
    public function run(): void
    {
        $quests = [
            ['quest' => 'Matikan lampu saat tidak digunakan di rumah', 'point' => 10],
            ['quest' => 'Gunakan botol minum isi ulang selama 7 hari', 'point' => 15],
            ['quest' => 'Pisahkan sampah organik dan anorganik di rumah', 'point' => 20],
            ['quest' => 'Bawa tas belanja sendiri saat belanja di pasar tradisional', 'point' => 12],
            ['quest' => 'Gunakan transportasi umum untuk pergi ke kantor', 'point' => 18],
            ['quest' => 'Bersihkan sampah di pantai selama 20 menit', 'point' => 25],
            ['quest' => 'Tanam pohon di sekitar sekolah', 'point' => 30],
            ['quest' => 'Kurangi penggunaan tisu sekali pakai selama 14 hari', 'point' => 16],
            ['quest' => 'Gunakan ulang kantong plastik bekas belanja selama 10 hari', 'point' => 15],
            ['quest' => 'Buat kompos dari sampah dapur selama 7 hari', 'point' => 22],
            ['quest' => 'Hindari menggunakan sedotan plastik saat minum di kampus', 'point' => 10],
            ['quest' => 'Ajak teman untuk ikut aksi bersih-bersih di taman kota', 'point' => 27],
            ['quest' => 'Gunakan energi alternatif di rumah seperti panel surya', 'point' => 40],
            ['quest' => 'Tidak membeli air minum dalam kemasan selama 14 hari', 'point' => 17],
            ['quest' => 'Hemat penggunaan air saat mandi dan mencuci', 'point' => 11],
            ['quest' => 'Gunakan lampu LED hemat energi di kamar tidur', 'point' => 9],
            ['quest' => 'Bawa tempat makan sendiri saat membeli makanan di luar', 'point' => 13],
            ['quest' => 'Gunakan baju bekas daripada membeli baru selama 2 minggu', 'point' => 20],
            ['quest' => 'Ikuti tantangan tanpa plastik selama 10 hari', 'point' => 21],
            ['quest' => 'Gunakan kertas bekas untuk catatan selama 5 hari', 'point' => 8],
            ['quest' => 'Bersihkan sampah di taman kota selama 15 menit', 'point' => 23],
            ['quest' => 'Matikan keran saat menggosok gigi', 'point' => 6],
            ['quest' => 'Gunakan aplikasi e-book daripada mencetak', 'point' => 14],
            ['quest' => 'Gunakan sabun batang daripada sabun cair kemasan plastik', 'point' => 12],
            ['quest' => 'Kurangi konsumsi daging merah selama 3 hari', 'point' => 19],
            ['quest' => 'Gunakan transportasi sepeda ke sekolah', 'point' => 26],
            ['quest' => 'Posting aksi peduli lingkungan di media sosial', 'point' => 9],
            ['quest' => 'Buat kampanye digital hemat energi', 'point' => 31],
            ['quest' => 'Gunakan daya listrik secara bijak saat jam sibuk', 'point' => 11],
            ['quest' => 'Tanam tanaman herbal di halaman rumah', 'point' => 24],
            ['quest' => 'Daur ulang botol plastik bekas', 'point' => 13],
            ['quest' => 'Gunakan ulang baju lama untuk keperluan rumah', 'point' => 15],
            ['quest' => 'Cuci pakaian dengan mode hemat air', 'point' => 10],
            ['quest' => 'Matikan peralatan elektronik saat tidak dipakai', 'point' => 14],
            ['quest' => 'Gunakan AC hanya saat benar-benar perlu', 'point' => 17],
            ['quest' => 'Simpan air hujan untuk menyiram tanaman', 'point' => 29],
            ['quest' => 'Bersihkan sampah di hutan kota selama 25 menit', 'point' => 27],
            ['quest' => 'Ajak tetangga membersihkan lingkungan rumah', 'point' => 18],
            ['quest' => 'Gunakan sabun ramah lingkungan', 'point' => 12],
            ['quest' => 'Buat rak tanaman dari bahan daur ulang', 'point' => 16],
            ['quest' => 'Tolak sedotan plastik saat beli minuman', 'point' => 7],
            ['quest' => 'Kurangi belanja produk berkemasan plastik', 'point' => 22],
            ['quest' => 'Gunakan kertas dua sisi untuk print', 'point' => 10],
            ['quest' => 'Tanam pohon di halaman sekolah', 'point' => 30],
            ['quest' => 'Ajarkan anak-anak memilah sampah', 'point' => 21],
            ['quest' => 'Berikan botol minum isi ulang ke orang lain', 'point' => 25],
            ['quest' => 'Gunakan kompor hemat energi', 'point' => 17],
            ['quest' => 'Perbaiki barang rusak daripada beli baru', 'point' => 14],
            ['quest' => 'Belanja produk lokal yang lebih ramah lingkungan', 'point' => 20],
            ['quest' => 'Kurangi penggunaan kendaraan pribadi', 'point' => 19],
            ['quest' => 'Bersihkan sungai dari sampah', 'point' => 28],
            ['quest' => 'Gunakan tempat sampah terpisah di rumah', 'point' => 16],
            ['quest' => 'Pasang lampu sensor gerak di teras', 'point' => 9],
            ['quest' => 'Menyiram tanaman di pagi hari agar hemat air', 'point' => 12],
            ['quest' => 'Kurangi penggunaan sabun cuci berbahan kimia', 'point' => 11],
            ['quest' => 'Gunakan air bekas cucian untuk menyiram halaman', 'point' => 15],
            ['quest' => 'Sosialisasi pentingnya daur ulang ke warga sekitar', 'point' => 24],
            ['quest' => 'Bersihkan selokan dari sampah plastik', 'point' => 19],
            ['quest' => 'Kurangi pemakaian kendaraan berbahan bakar fosil', 'point' => 21],
            ['quest' => 'Tanam pohon di taman umum', 'point' => 30],
            ['quest' => 'Gunakan aplikasi digital untuk catatan harian', 'point' => 13],
            ['quest' => 'Daur ulang kardus bekas pembelian online', 'point' => 18],
            ['quest' => 'Gunakan tas jinjing kain ke minimarket', 'point' => 14],
            ['quest' => 'Ajarkan anak-anak cara membuat kompos', 'point' => 20],
            ['quest' => 'Gunakan energi angin sebagai alternatif', 'point' => 35],
            ['quest' => 'Gunakan air galon isi ulang daripada botol sekali pakai', 'point' => 15],
            ['quest' => 'Kumpulkan minyak jelantah untuk didaur ulang', 'point' => 23],
            ['quest' => 'Buat tempat sampah kompos di rumah', 'point' => 22],
            ['quest' => 'Gunakan produk rumah tangga tanpa fosfat', 'point' => 12],
            ['quest' => 'Dukung kampanye pelestarian alam lokal', 'point' => 29],
            ['quest' => 'Gunakan transportasi daring berbasis listrik', 'point' => 17],
            ['quest' => 'Bersihkan area sekitar kampus dari sampah', 'point' => 18],
            ['quest' => 'Buat konten edukatif tentang lingkungan', 'point' => 26],
            ['quest' => 'Sumbangkan pakaian bekas layak pakai', 'point' => 19],
            ['quest' => 'Gunakan sabun organik untuk mandi', 'point' => 13],
            ['quest' => 'Kumpulkan limbah elektronik bekas untuk didaur ulang', 'point' => 28],
            ['quest' => 'Ganti lampu rumah dengan LED hemat energi', 'point' => 10],
            ['quest' => 'Ikuti tantangan #ZeroWaste selama seminggu', 'point' => 32],
            ['quest' => 'Tonton dan bagikan dokumenter tentang lingkungan', 'point' => 12],
            ['quest' => 'Gunakan kembali wadah makanan bekas', 'point' => 14],
            ['quest' => 'Bersihkan sampah di sekitar halte bus', 'point' => 22],
            ['quest' => 'Bersihkan area taman bersama komunitas', 'point' => 25],
            ['quest' => 'Gunakan kertas daur ulang untuk keperluan kantor', 'point' => 11],
            ['quest' => 'Tanam pohon rindang di sekitar rumah', 'point' => 30],
            ['quest' => 'Buat lubang biopori di halaman rumah', 'point' => 18],
            ['quest' => 'Jual barang bekas daripada dibuang', 'point' => 21],
            ['quest' => 'Gunakan produk refill daripada beli kemasan baru', 'point' => 16],
            ['quest' => 'Kurangi pemakaian tisu basah', 'point' => 10],
            ['quest' => 'Bersihkan area parkir dari sampah plastik', 'point' => 15],
            ['quest' => 'Gunakan sabun cuci piring ramah lingkungan', 'point' => 11],
            ['quest' => 'Tanam bunga untuk mendukung populasi lebah', 'point' => 27],
            ['quest' => 'Gunakan sistem tanam hidroponik sederhana', 'point' => 26],
            ['quest' => 'Gunakan energi biogas dari sampah organik', 'point' => 33],
            ['quest' => 'Gunakan baterai isi ulang', 'point' => 20],
            ['quest' => 'Gunakan kompor induksi hemat energi', 'point' => 17],
            ['quest' => 'Pasang timer untuk pemanas air', 'point' => 13],
            ['quest' => 'Bersihkan saluran air dari sampah', 'point' => 22],
            ['quest' => 'Buat tantangan hemat listrik keluarga', 'point' => 28],
            ['quest' => 'Daur ulang koran lama menjadi kerajinan', 'point' => 24],
            ['quest' => 'Gunakan sabun cuci pakaian ramah lingkungan', 'point' => 14],
            ['quest' => 'Buat video kampanye anti-sampah plastik', 'point' => 26],
            ['quest' => 'Pasang panel surya mini untuk lampu taman', 'point' => 36],
            ['quest' => 'Kurangi penggunaan plastik selama 7 hari', 'point' => 18],
            ['quest' => 'Buat video edukasi tentang perubahan iklim dan bagikan ke media sosial', 'point' => 25],
            ['quest' => 'Bersihkan area selokan dari sampah', 'point' => 30],
            ['quest' => 'Tanam pohon mangga di halaman rumah', 'point' => 35],
            ['quest' => 'Ajak teman untuk mengikuti tantangan tanpa plastik', 'point' => 20],
            ['quest' => 'Ganti penggunaan kantong plastik dengan tas kain', 'point' => 12],
            ['quest' => 'Gunakan transportasi sepeda ke pasar selama 5 hari', 'point' => 21],
            ['quest' => 'Buat kerajinan dari kardus bekas', 'point' => 19],
            ['quest' => 'Simpan air hujan untuk menyiram tanaman', 'point' => 24],
            ['quest' => 'Ikuti webinar tentang energi terbarukan', 'point' => 16],
            ['quest' => 'Kumpulkan dan daur ulang baterai bekas', 'point' => 29],
            ['quest' => 'Dukung petani lokal dengan membeli produk organik', 'point' => 15],
            ['quest' => 'Gunakan botol minum isi ulang saat belanja di supermarket', 'point' => 13],
            ['quest' => 'Buat taman kecil di pekarangan', 'point' => 20],
            ['quest' => 'Tidak menggunakan plastik sama sekali di hari Senin', 'point' => 14],
            ['quest' => 'Gunakan kembali rak buku yang rusak dengan diperbaiki', 'point' => 22],
            ['quest' => 'Ubah ruang kerja jadi lebih ramah lingkungan', 'point' => 26],
            ['quest' => 'Sumbangkan mainan yang masih layak pakai', 'point' => 18],
            ['quest' => 'Gunakan air bekas mencuci untuk membersihkan lantai', 'point' => 17],
            ['quest' => 'Ajarkan anak-anak tentang penghematan energi', 'point' => 23],
        ];
    
        foreach ($quests as $quest) {
            Quest::factory()->create($quest);
        }
    }

    
}

